import { useState } from 'react';
import { ArrowRight, Calculator, CalendarDays, Check, CircleHelp, Clock3, FileText, FlaskConical, History, Layers3, Plus, RotateCcw, ShieldCheck, Trash2, TrendingUp, TriangleAlert } from 'lucide-react';
import { Badge, EmptyState, Notice, PanelHeader, TeamCrest } from './UI.jsx';
import { decimal, percent, DEFAULT_PARAMETERS } from '../lib/data.js';
import { couponTotals, predict } from '../lib/model.js';

export function ComparePage({ coupon, onUpdate, onRemove, onLoadExample, onAddManual, onGoAnalysis }) {
  const summary = couponTotals(coupon);
  return <>
    <div className="page-heading"><div><div className="eyebrow">COMPARATEUR DE COTES</div><h1>Le bon prix fait la différence.</h1><p>Une cote n’est pas une prédiction. Regardez ce qu’elle exige réellement.</p></div><button className="button button-primary" onClick={onAddManual} disabled={coupon.length >= 8}><Plus size={17} /> Ajouter une sélection</button></div>
    {!coupon.length ? <section className="panel"><EmptyState icon={Calculator} title="Votre comparateur est prêt." description="Ajoutez une sélection de votre analyse ou retrouvez le coupon NVSL présent dans votre capture. Aucun score ni résultat n’en sera déduit."><div className="empty-actions"><button className="button button-primary" onClick={onLoadExample}>Charger le coupon de la capture <ArrowRight size={16} /></button><button className="button button-secondary" onClick={onGoAnalysis}>Explorer les marchés</button></div></EmptyState></section> : <>
      <div className="coupon-summary"><div className="coupon-price"><span className="eyebrow">COTE TOTALE THÉORIQUE</span><strong>{summary.valid ? decimal(summary.combinedOdds, 3) : '—'}</strong><p>{coupon.length} sélection{coupon.length > 1 ? 's' : ''} · prix multipliés</p></div><div className="coupon-summary-stat"><span>Seuil d’équilibre</span><strong>{summary.valid ? percent(summary.breakEven) : '—'}</strong><small>Taux de réussite nécessaire à cette cote</small></div><div className="coupon-summary-stat"><span>Probabilité estimée du combiné</span><strong>{summary.complete ? percent(summary.jointProbability) : '—'}</strong><small>{summary.complete ? 'Sous hypothèse d’indépendance' : 'Estimations manquantes ou non combinables'}</small></div></div>
      <section className="panel coupon-panel"><PanelHeader title="Vos sélections" description="Les prix de la capture peuvent avoir changé. Vérifiez-les chez le bookmaker."><Badge>{coupon.length} / 8 sélections</Badge></PanelHeader><div className="coupon-table-heading"><span>Match & marché</span><span>Cote proposée</span><span>Estimation indépendante</span><span /></div>
        {coupon.map(entry => <div className="coupon-row" key={entry.id}><div className="coupon-fixture"><strong>{entry.fixture}</strong><span>{entry.market}</span><small>{entry.date || 'Simulation · pas un match en direct'}</small></div><label className="coupon-number"><span className="mobile-label">Cote</span><input aria-label={`Cote — ${entry.fixture}`} type="text" inputMode="decimal" maxLength={10} value={entry.odds} onChange={e => onUpdate(entry.id, 'odds', e.target.value)} /></label><label className="coupon-number probability-number"><span className="mobile-label">Probabilité estimée</span><div><input aria-label={`Probabilité — ${entry.fixture}`} type="text" inputMode="decimal" maxLength={7} placeholder="À renseigner" value={entry.probability} onChange={e => onUpdate(entry.id, 'probability', e.target.value)} /><span>%</span></div></label><button className="icon-button" aria-label={`Retirer ${entry.fixture}`} onClick={() => onRemove(entry.id)}><Trash2 size={17} /></button></div>)}
        <div className="coupon-table-footer"><button className="text-button" onClick={onAddManual} disabled={coupon.length >= 8}><Plus size={16} /> Ajouter une sélection</button><span>Ne déduisez pas votre estimation de 1 ÷ cote.</span></div>
      </section>
      {!summary.valid && <Notice kind="warning">{summary.error}</Notice>}
      {summary.correlated && <Notice kind="warning">Plusieurs sélections concernent le même match. Leurs probabilités ne sont pas indépendantes : la probabilité combinée est volontairement désactivée.</Notice>}
      {summary.invalidProbability && <Notice kind="warning">Une probabilité saisie n’est pas valide. Utilisez une valeur entre 0 et 100 %.</Notice>}
      {summary.valid && <div className="comparison-insight"><div className="insight-icon"><FlaskConical size={25} /></div><div><h3>{summary.complete ? (summary.expectedReturn >= 0 ? 'Écart théorique favorable — à vérifier' : 'Le prix ne compense pas le risque estimé') : 'Sans statistiques, pas de prédiction fiable.'}</h3><p>{summary.complete ? `L’espérance selon vos estimations est de ${decimal(summary.expectedReturn * 100, 1)} % par unité misée. Ce résultat est conditionnel : un modèle non calibré ou une estimation trop optimiste peut inverser le verdict.` : 'Le coupon NVSL indique des cotes et un statut « Accepté », mais aucun score ni statistique de match. L’application n’invente donc pas les probabilités manquantes et ne déclare pas le coupon gagnant.'}</p></div></div>}
    </>}
    <Notice><strong>Important :</strong> combiner des paris augmente le risque de tout perdre. Les cotes totales sont indicatives, hors frais éventuels et conditions promotionnelles. L’outil ne place aucun pari.</Notice>
  </>;
}

export function HistoryPage({ history, onLoad, onDelete, onGoAnalysis }) {
  return <><div className="page-heading"><div><div className="eyebrow">BIBLIOTHÈQUE PERSONNELLE</div><h1>Vos analyses, au même endroit.</h1><p>Des instantanés de vos données et paramètres, conservés sur cet appareil.</p></div><Badge icon={ShieldCheck}>Stockage local</Badge></div>{!history.length ? <section className="panel"><EmptyState icon={History} title="L’histoire commence par un match." description="Enregistrez une analyse depuis le tableau de bord pour la retrouver ici. Seules les statistiques sont sauvegardées, pas les images."><button className="button button-primary" onClick={onGoAnalysis}>Ouvrir mon analyse <ArrowRight size={16} /></button></EmptyState></section> : <div className="history-grid">{history.map(entry => {
    const prediction = predict(entry.match, entry.parameters); const top = prediction.scores?.[0];
    return <section className="panel history-card" key={entry.id}><div className="history-card-top"><Badge icon={Clock3}>{entry.match.sampleConfirmed ? 'Données confirmées' : 'Volume à confirmer'}</Badge><button className="icon-button" aria-label={`Supprimer l’analyse ${entry.match.home.name} — ${entry.match.away.name}`} onClick={() => onDelete(entry.id)}><Trash2 size={16} /></button></div><div className="history-fixture"><TeamCrest team={entry.match.home} size="small" /><div><strong>{entry.match.home.name}<span>vs</span>{entry.match.away.name}</strong><small>{entry.match.competition} · {entry.match.season}</small></div><TeamCrest team={entry.match.away} size="small" /></div><div className="history-result"><span>Score modal <b>{top ? `${top.home}–${top.away}` : '—'}</b></span><span>Sa probabilité <b>{top ? percent(top.probability) : '—'}</b></span></div><div className="history-card-bottom"><small>{Number.isNaN(Date.parse(entry.createdAt)) ? 'Date inconnue' : new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(entry.createdAt))}</small><button className="text-button" onClick={() => onLoad(entry)}>Reprendre <ArrowRight size={15} /></button></div></section>;
  })}</div>}</>;
}

export function MethodPage({ parameters, setParameters, onResetExample }) {
  return <><div className="page-heading"><div><div className="eyebrow">SOUS LE CAPOT</div><h1>Comprendre avant de prédire.</h1><p>Pas de boîte noire. Voici exactement ce que le modèle fait — et ne fait pas.</p></div><Badge kind="green" icon={FlaskConical}>Modèle exploratoire v1</Badge></div>
    <div className="method-intro"><div><span className="eyebrow">NOTRE APPROCHE</span><h2>La donnée, pas le hasard.<br /><span>Et surtout, pas de certitude.</span></h2><p>MatchLab transforme des moyennes et des xG en distributions de scores avec deux lois de Poisson indépendantes. Les paramètres sont heuristiques : le modèle n’a pas été entraîné ni validé sur un historique de championnat.</p></div><div className="method-symbol"><FlaskConical size={78} strokeWidth={1.2} /><span>λ₁ × λ₂</span></div></div>
    <div className="method-steps">{[
      ['01', 'Remettre les xG à la bonne échelle', 'Un total de 8,5 xG sur 5 matchs vaut 1,7 xG par match. Les totaux de saison ne doivent pas être utilisés comme des moyennes. Le nombre de matchs n’est pas déduit des 5 derniers résultats.'],
      ['02', 'Construire deux intensités de buts', 'L’attaque combine xG créés et buts marqués. La défense combine xG concédés et buts encaissés. Les petits échantillons sont rapprochés d’une référence générique, puis attaque et défense adverse sont combinées par moyenne géométrique.'],
      ['03', 'Distribuer les scores possibles', 'Chaque score reçoit P(H=h) × P(A=a). Les cases sont additionnées pour obtenir victoire, nul, double chance, totaux et « les deux équipes marquent ». Le score modal est seulement la case la plus probable.'],
      ['04', 'Comparer une probabilité à un prix', 'Une cote de 1,25 exige 80 % de réussite pour atteindre l’équilibre. La cote neutre vaut 1 ÷ probabilité. Un écart favorable selon un modèle non calibré ne suffit pas à prouver la rentabilité.'],
    ].map(([n,title,text]) => <section className="panel method-step" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></section>)}</div>
    <section className="panel settings-panel"><PanelHeader title="Réglez les hypothèses" description="Ces réglages affectent immédiatement votre analyse. Ils ne sont pas des paramètres calibrés."><button className="text-button" onClick={() => setParameters({ ...DEFAULT_PARAMETERS })}><RotateCcw size={15} /> Valeurs par défaut</button></PanelHeader><div className="parameter-grid">{[
      ['xgWeight', 'Poids des xG', 0, 1, 0.05, 'Le reste du poids est donné aux buts réellement inscrits et encaissés.', value => percent(value, 0)],
      ['priorMatches', 'Lissage des petits échantillons', 0, 20, 1, 'Nombre de matchs fictifs à la référence générique. Plus il est élevé, plus le modèle atténue les extrêmes.', value => `${value} matchs`],
      ['homeAdvantage', 'Bonus de l’équipe à domicile', 0, 0.4, 0.01, 'S’applique à son intensité de buts. Désactivé sur terrain neutre.', value => `+${percent(value, 0)}`],
      ['awayPenalty', 'Réduction de l’équipe extérieure', 0, 0.4, 0.01, 'S’applique à son intensité de buts. Désactivée sur terrain neutre.', value => `−${percent(value, 0)}`],
      ['baseline', 'Référence générique de buts', 0.1, 4, 0.05, 'Une hypothèse de lissage, pas la moyenne observée de Premier League 2026/2027.', value => decimal(value)],
    ].map(([key,label,min,max,step,hint,format]) => <label className="parameter-control" key={key}><span>{label}<b>{format(parameters[key])}</b></span><input aria-label={label} type="range" min={min} max={max} step={step} value={parameters[key]} onChange={e => setParameters(current => ({ ...current, [key]: Number(e.target.value) }))} /><small>{hint}</small></label>)}</div><div className="formula-box"><code>attaque = poids × xG/match + (1 − poids) × buts/match<br />λ₁ = √(attaque₁ lissée × défense₂ lissée) × bonus domicile<br />λ₂ = √(attaque₂ lissée × défense₁ lissée) × réduction extérieure<br />P(k buts) = exp(−λ) × λᵏ / k!</code></div></section>
    <div className="method-notes"><section className="panel"><h3><Layers3 size={19} /> Ce que montrent vos captures</h3><p>Les trois captures FotMob alimentent l’exemple Arsenal–Leeds. Les 13 confrontations (11 victoires d’Arsenal, 2 nuls) sont conservées comme contexte, sans être transformées en probabilité de victoire.</p><p>La capture du coupon NVSL est distincte : elle fournit trois cotes « plus de 3,5 buts », pas des statistiques ni des résultats.</p><button className="text-button" onClick={onResetExample}>Recharger l’exemple des captures <ArrowRight size={15} /></button></section><section className="panel"><h3><TriangleAlert size={19} /> Les limites à garder en tête</h3><p>Pas de flux FotMob en direct, de blessures, de compositions, de météo, de différence domicile/extérieur mesurée, de force des adversaires ou de calibration historique. Les buts des deux équipes ne sont pas réellement toujours indépendants.</p><p>La possession, les tirs, la forme et les confrontations sont affichés mais exclus du calcul pour ne pas recompter arbitrairement l’information déjà contenue dans les xG.</p></section></div>
    <Notice><strong>18+ · Jeu responsable.</strong> Aucun score ni gain n’est garanti. N’utilisez pas ce modèle comme unique motif d’un pari, ne misez pas d’argent indispensable et ne cherchez pas à récupérer une perte en augmentant vos mises.</Notice>
  </>;
}
